d_chain = {'default':
           {'n':
            {'subSteps':12,
            'maxCollisionIterations':49,
            'gravity':98,
            'gravityDirection':[0,-1,0]},
            'hs':
            {'bendFollow':1.0,
             'hairWidth':1.2,
             'solverDisplay':1,
             'stretchResistance':105,
             'drag':.1,
             'tangentalDrag':.1,
             }
            },
           'wind':
           {'n':
            {'windSpeed':900,
                        'windDirection':[0,0,-1],
                        'windNoise':5},
            'hs':{'intensity':1.0,
                  'frequency':5.0,
                  'speed':.2}}}