import cgm.core
cgm.core._reload()
from cgm.core import cgm_Meta as cgmMeta
from cgm.core import cgm_PuppetMeta as cgmPM
import Red9.core.Red9_Meta as r9Meta
from cgm.core.rigger import RigFactory as Rig
#======================================================================
cgm.core._reload()
cgmMeta.log.setLevel(cgmMeta.logging.INFO)
mFactory.log.setLevel(mFactory.logging.DEBUG)
spine = r9Meta.MetaClass('spine_part')
spine.setState('skeleton',forceNew=True)
spine.rig_getSkinJoints()
spine.doRig()
spine.isRigged()
spine.doSkeletonize()
spine.doRig()
spine.rig_getSkinJoints(False)
spine.rig_getHandleJoints(False)
spine.rig_getRigHandleJoints(False)
Rig.get_rigDeformationJoints(spine)
Rig.get_rigJointDriversDict(spine)
Rig.get_simpleRigJointDriverDict(spine)

spine.rig_getRigHandleJoints(False)
spine.setState('skeleton',forceNew=True)
reload(Rig)
Rig.get_report(spine)
spine.rig_getHandleJoints()
spine.rigConnect()
spine.isRigged()
spine.isRigConnected()
spine.getState()
spine.rigDelete()
spine.doRig()
spine.rig_getSkinJoints()
reload(Rig)
i_rig = Rig.go(spine,forceNew=False,autoBuild = False)#call to do general rig
i_rig.doBuild('')
i_rig.build(i_rig,buildTo = '')
i_rig.isShaped()
i_rig.buildModule.build_shapes(i_rig)
i_rig.buildModule.build_rigSkeleton(i_rig)
i_rig.buildModule.build_controls(i_rig)
i_rig.buildModule.build_deformation(i_rig)
i_rig.buildModule.build_rig(i_rig)
Rig.get_report(spine)
spine.doRig()
spine.rigDelete()
reload(Rig)